language: go
go:
  - 1.11.x

env:
  - GO111MODULE=on

install: true

jobs:
  include:
    - stage: test
      script: go test -v -mod=vendor ./...

    # Define a stage that will auto-generate CloudFormation resources from the official
    # AWS CloudFormation Resource Specification on a daily basis (run via a travis cron)
    - stage: regenerate
      if: type = cron
      script: generate/create-pull-request.sh

    # Define the release stage that runs semantic-release
    - stage: release
      if: branch = master
      language: node_js
      node_js: lts/*
      before_install: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          # Install tool for updating AUTHORS.md
          # Update the AUTHORS.md file
          - go get github.com/myii/maintainer
          - maintainer contributor

          # Install all dependencies required for `semantic-release`
          - npm install @semantic-release/changelog@3 -D
          - npm install @semantic-release/exec@3 -D
          - npm install @semantic-release/git@7 -D

          # Run `semantic-release`
          - npx semantic-release@15
